Clase 1(d) - Análisis de Firmas Espectrales
============================================

### SoPI II: Herramientas de teledetección cuantitativa

En esta clase nos centraremos en el análisis de firmas espectrales. 

Se utilizara este notebook de python para ayudar en el procesamiento y la visualización de las mismas.

Los notebooks se dividen de la siguiente manera

- (a) - Grafico de valores de reflectancia por banda
- (b) - Grafico de firmas espectrales
- (c) - Calculo de $\rho_i$ a partir de una firma espectral
- **(d)** - Descomposición de firmas especrales

### Carga de librerias

Recuerde que debe ejecutar **siempre** primero la celda que carga las librerias para ejecutar los procesos.

In [4]:
# Cargamos las librerais
import numpy as np
import matplotlib.pyplot as plt

# Fijamos que muestre los graficos dentro de la linea
%matplotlib inline

### Descomposición de firmas espectrales

Apuntamos ahora a descomponer la firma espectral de un pixel a partir de conocer las firmas espectrales puras para la zona.

Debemos en primer lugar cargar cada una de ellas como un vector para poder utilizarlas

In [36]:
# Cargamos las firmas espectrales como arrays de numpy

v = np.array([0.05,0.1,0.05,0.4,0.2,0.1,1])
s = np.array([0.05,0.1,0.15,0.2,0.3,0.4,1])
a = np.array([0.05,0.04,0.01,0.,0.,0.,1])

In [37]:
# Fijamos que la suma de  las 3 variables sea siempre 1
M = np.matrix([v,s,a])
a = M.T*np.matrix([0.5,0.3,0.2]).T

In [41]:
a = np.matrix([0.5,0.2,0.1,0.3,0.2,0.1,1])
np.linalg.lstsq(M.T,a.T)

(matrix([[ 0.72464613],
         [ 0.14365878],
         [ 0.15880631]]),
 matrix([[ 0.21646228]]),
 3,
 array([ 1.82854536,  0.38118034,  0.25558443]))