Clase 1(d) - Análisis de Firmas Espectrales
============================================

### SoPI II: Herramientas de teledetección cuantitativa

En esta clase nos centraremos en el análisis de firmas espectrales. 

Se utilizara este notebook de python para ayudar en el procesamiento y la visualización de las mismas.

Los notebooks se dividen de la siguiente manera

- (a) - Grafico de valores de reflectancia por banda
- (b) - Grafico de firmas espectrales
- (c) - Calculo de $\rho_i$ a partir de una firma espectral
- **(d)** - Descomposición de firmas especrales

### Carga de librerias

Recuerde que debe ejecutar **siempre** primero la celda que carga las librerias para ejecutar los procesos.

In [1]:
# Cargamos las librerais
import numpy as np
import matplotlib.pyplot as plt

# Fijamos que muestre los graficos dentro de la linea
%matplotlib inline

### Descomposición de firmas espectrales

Apuntamos ahora a descomponer la firma espectral de un pixel a partir de conocer las firmas espectrales puras para la zona.

Debemos en primer lugar cargar cada una de ellas como un vector para poder utilizarlas

In [11]:
# Cargamos las firmas espectrales como arrays de numpy

a = np.array([0.08,0.03,0.01,0.00,0.00,0.00])
n = np.array([0.95,1.00,1.00,0.78,0.02,0.01])
s = np.array([0.08,0.11,0.14,0.18,0.22,0.20])
v = np.array([0.01,0.03,0.02,0.28,0.11,0.04])

y a partir de estos vectores crear la matriz que relaciona las coberturas con la firma espectral

In [13]:
# Creamos la matriz de vectores
M = np.array([v,s,a,n])
# Fijamos que la suma de  las 3 variables sea siempre 1
o = np.ones(M.shape[0])
M = np.vstack((M.T,o))
M = np.matrix(M)

In [14]:
# Cargamos el vector de mediciones
pixel = np.array([0.5,0.2,0.1,0.3,0.2,0.1])
# Le agregamos el valor uno al final. Esto es importante para forzar la suma a 1
pixel = np.append(pixel,1)
pixel = np.matrix(pixel)

In [15]:
np.linalg.pinv(M)*pixel.T

matrix([[ 0.11770807],
        [ 0.40956208],
        [ 0.27792042],
        [ 0.21055827]])

In [16]:
sum(np.linalg.pinv(M)*pixel.T)

matrix([[ 1.01574884]])

In [19]:
np.linalg.lstsq(M,pixel.T)

(matrix([[ 0.11770807],
         [ 0.40956208],
         [ 0.27792042],
         [ 0.21055827]]),
 matrix([[ 0.10374967]]),
 4,
 array([ 2.48574703,  1.22575889,  0.24415079,  0.17368718]))